// char* TOKENS_STRING[] = {

//         "integer",
//         "real",
//         "boolean",
//         "of",
//         "array",
//         "start",
//         "end",
//         "declare",
//         "module",
//         "driver",
//         "program",
//         "get_value",
//         "print",
//         "use",
//         "with",
//         "parameters",
//         "takes",
//         "input",
//         "returns",
//         "for",
//         "in",
//         "switch",
//         "case",
//         "break",
//         "default",
//         "while",
//         "AND",
//         "OR",
//         "true",
//         "false",
//         "+",
//         "-",
//         "*",
//         "/",
//         "<",
//         "<=",
//         ">=",
//         ">",
//         "==",
//         "!=",
//         "<<",
//         ">>",
//         "<<<",
//         ">>>",
//         ":",
//         "..",
//         ";",
//         ",",
//         ":=",
//         "[",
//         "]",
//         "(",
//         ")",
//     };

char* TERMINALS_STRINGS[] = {
    "INTEGER",
    "REAL",
    "BOOLEAN",
    "OF",
    "ARRAY",
    "START",
    "END",
    "DECLARE",
    "MODULE",
    "DRIVER",
    "PROGRAM",
    "GET_VALUE",
    "PRINT",
    "USE",
    "WITH",
    "PARAMETERS",
    "TAKES",
    "INPUT",
    "RETURNS",
    "FOR",
    "IN",
    "SWITCH",
    "CASE",
    "BREAK",
    "DEFAULT",
    "WHILE",
    "AND",
    "OR",
    "true",
    "false",
    "PLUS",
    "MINUS",
    "MUL",
    "DIV",
    "LT",
    "LE",
    "GE",
    "GT",
    "EQ",
    "NE",
    "DEF",
    "ENDDEF",
    "DRIVERDEF",
    "DRIVERENDDEF",
    "COLON",
    "RANGEOP",
    "SEMICOL",
    "COMMA",
    "ASSIGNOP",
    "SQBO",
    "SQBC",
    "BO",
    "BC",
    "EOF",
    "ID",
    "NUM",
    "RNUM",
};

char* NONTERMINALS_STRINGS[] = {
    "finalProgram",
    "program",
    "moduleDeclarations",
    "moduleDeclaration",
    "otherModules",
    "driverModule",
    "module",
    "ret",
    "input_plist",
    "leftFactored_input_plist",
    "output_plist",
    "leftFactored_output_plist",
    "dataType",
    "arrRange",
    "leftFactored_arrRange",
    "sign",
    "type",
    "moduleDef",
    "statements",
    "statement",
    "ioStmt",
    "leftFactored_ioStmt",
    "boolValues",
    "var",
    "whichId",
    "leftFactored_whichId",
    "simpleStmt",
    "assignmentStmt",
    "whichStmt",
    "lvalueIDStmt",
    "lvalueARRStmt",
    "moduleReuseStmt",
    "optional",
    "idList",
    "leftFactored_idList",
    "expression",
    "unaryTerm",
    "arithmeticFactor",
    "arithmeticBooleanExpr",
    "logicalTerm",
    "relationalTerm",
    "arithmeticExpr",
    "leftFactored_arithmeticExpr",
    "pm",
    "md",
    "term",
    "leftFactored_term",
    "factor",
    "arithmeticExprWArr",
    "leftFactored_arithmeticExprWArr",
    "termWArr",
    "leftFactored_termWArr",
    "signedFactorWArr",
    "factorWArr",
    "logicalOp",
    "relationalOp",
    "declareStmt",
    "conditionalStmt",
    "caseStmt",
    "leftFactored_caseStmt",
    "value",
    "dfault",
    "iterativeStmt",
    "param",
    "arrID",
    "paramList",
    "leftFactored_paramList",
    "signedParam",
    "anyTerm",
    "idNum"
};