#ifndef SYMTAB_H
#define SYMTAB_H
#include "symbolTableDef.h"

SYMBOLTABLE initializeSymbolTable(char* name);
SYMBOLTABLEROW StoreVarAsInputParam(SYMBOLTABLEROW IP,TREENODE var);
SYMBOLTABLEROW StoreVarAsOutputParam(SYMBOLTABLEROW OP,TREENODE var);
void StoreVarIntoSymbolTable(SYMBOLTABLE SYMBOLTABLE,TREENODE var);
SYMBOLTABLEROW StoreFuncIntoSymbolTable(SYMBOLTABLE SYMBOLTABLE,TREENODE func);
SYMBOLTABLEROW GetVarFromSymbolTable(SYMBOLTABLE SYMBOLTABLE,TREENODE var);
SYMBOLTABLEROW GetFuncFromSymbolTable(SYMBOLTABLE SYMBOLTABLE,TREENODE func);
void printSymbolTable(SYMBOLTABLEROW func);
#endif