#ifndef SYMTAB_H
#define SYMTAB_H
#include "symbolTableDef.h"

SYMBOLTABLEROW* initializeSymbolTable();
void StoreVarIntoSymbolTable(SYMBOLTABLEROW* SYMBOLTABLE,TREENODE var);
SYMBOLTABLEROW StoreFuncIntoSymbolTable(SYMBOLTABLEROW* SYMBOLTABLE,TREENODE func);
SYMBOLTABLEROW GetVarFromSymbolTable(SYMBOLTABLEROW* SYMBOLTABLE,TREENODE var);
SYMBOLTABLEROW GetFuncFromSymbolTable(SYMBOLTABLEROW* SYMBOLTABLE,TREENODE func);
void printSymbolTable(SYMBOLTABLEROW* SYMBOLTABLE);
#endif