/*

^   24/02
*REQUIRES:
    TODO: FILE HANDLING OF grammar.txt => MADHAV    25/02 
    TODO: TERMINAL AND NONTERMINAL ARRAYS => RUCHI  24/02 IN PROGRESS
    &DONE: LINKEDLIST ADT

~PRODUCES AN ARRAY OF LINKED LIST HAVING RULES STORED IN IT

*/