
#include "../../utils/tokens/tokens.h"

TOKENS* firstFollowSet[] = {
    {DECLARE_KEYWORD,DEF_OPERATOR,DRIVERDEF_OPERATOR},
    {DECLARE_KEYWORD,DEF_OPERATOR,DRIVERDEF_OPERATOR},
    {DECLARE_KEYWORD},
    {DEF_OPERATOR,DRIVERDEF_OPERATOR},
    {DECLARE_KEYWORD},
    {DEF_OPERATOR},
    {DRIVERDEF_OPERATOR,EOF_TOKEN},
    {DRIVERDEF_OPERATOR},
    {DEF_OPERATOR},
    {RETURNS_KEYWORD},
    {START_KEYWORD},
    {IDENTIFIER_TOKEN},
    {COMMA_OPERATOR},
    {SQBC_TOKEN},
    {IDENTIFIER_TOKEN},
    {COMMA_OPERATOR},
    {SQBC_TOKEN},
    {INTEGER_TYPE},
    {REAL_TYPE},
    {BOOLEAN_TYPE},
    {ARRAY_KEYWORD},
    {PLUS_OPERATOR,MINUS_OPERATOR,IDENTIFIER_TOKEN,NUM_TOKEN,RNUM_TOKEN}

};